"""Common utilities and resources for Weighted Go."""

from .resources import (
    # Symbols
    SYMBOL_BLACK_STONE,
    SYMBOL_WHITE_STONE,
    SYMBOL_BLACK_TERRITORY,
    SYMBOL_WHITE_TERRITORY,
    SYMBOL_CONTESTED,
    SYMBOL_EMPTY,
    get_symbol_legend,
    # ANSI Colors - Basic
    ANSI_RESET,
    ANSI_BOLD,
    ANSI_DIM,
    ANSI_ITALIC,
    ANSI_UNDERLINE,
    # ANSI Colors - Foreground
    ANSI_FG_BLACK,
    ANSI_FG_RED,
    ANSI_FG_GREEN,
    ANSI_FG_YELLOW,
    ANSI_FG_BLUE,
    ANSI_FG_MAGENTA,
    ANSI_FG_CYAN,
    ANSI_FG_WHITE,
    ANSI_FG_BRIGHT_BLACK,
    ANSI_FG_BRIGHT_WHITE,
    # ANSI Colors - Background
    ANSI_BG_BLACK,
    ANSI_BG_WHITE,
    ANSI_BG_YELLOW,
    # Color scheme for Go
    COLOR_BLACK_STONE,
    COLOR_WHITE_STONE,
    COLOR_BLACK_TERRITORY,
    COLOR_WHITE_TERRITORY,
    COLOR_CONTESTED,
    COLOR_BOARD_BACKGROUND,
    COLOR_LAST_MOVE,
    COLOR_WINNER,
    # Helper functions
    is_terminal,
    colorize,
    strip_ansi,
    colored_stone,
    rgb_fg,
    rgb_bg,
    color_256_fg,
    color_256_bg,
)

__all__ = [
    # Symbols
    "SYMBOL_BLACK_STONE",
    "SYMBOL_WHITE_STONE",
    "SYMBOL_BLACK_TERRITORY",
    "SYMBOL_WHITE_TERRITORY",
    "SYMBOL_CONTESTED",
    "SYMBOL_EMPTY",
    "get_symbol_legend",
    # ANSI Colors
    "ANSI_RESET",
    "ANSI_BOLD",
    "ANSI_DIM",
    "ANSI_ITALIC",
    "ANSI_UNDERLINE",
    "ANSI_FG_BLACK",
    "ANSI_FG_RED",
    "ANSI_FG_GREEN",
    "ANSI_FG_YELLOW",
    "ANSI_FG_BLUE",
    "ANSI_FG_MAGENTA",
    "ANSI_FG_CYAN",
    "ANSI_FG_WHITE",
    "ANSI_FG_BRIGHT_BLACK",
    "ANSI_FG_BRIGHT_WHITE",
    "ANSI_BG_BLACK",
    "ANSI_BG_WHITE",
    "ANSI_BG_YELLOW",
    # Go color scheme
    "COLOR_BLACK_STONE",
    "COLOR_WHITE_STONE",
    "COLOR_BLACK_TERRITORY",
    "COLOR_WHITE_TERRITORY",
    "COLOR_CONTESTED",
    "COLOR_BOARD_BACKGROUND",
    "COLOR_LAST_MOVE",
    "COLOR_WINNER",
    # Helper functions
    "is_terminal",
    "colorize",
    "strip_ansi",
    "colored_stone",
    "rgb_fg",
    "rgb_bg",
    "color_256_fg",
    "color_256_bg",
]
