"""
Display symbols and resources for Weighted Go visualization.

DEPRECATED: This module re-exports from symbols.py and cli_colors.py for backward compatibility.
New code should import directly from those modules.
"""

# Re-export symbols
from .symbols import (
    SYMBOL_BLACK_STONE,
    SYMBOL_WHITE_STONE,
    SYMBOL_BLACK_TERRITORY,
    SYMBOL_WHITE_TERRITORY,
    SYMBOL_CONTESTED,
    SYMBOL_EMPTY,
    SYMBOL_DISPLAY_WIDTH,
    get_symbol_legend,
)

# Re-export CLI colors
from .cli_colors import (
    # ANSI Control Sequences
    ANSI_RESET,
    ANSI_BOLD,
    ANSI_DIM,
    ANSI_ITALIC,
    ANSI_UNDERLINE,
    ANSI_BLINK,
    ANSI_REVERSE,
    ANSI_HIDDEN,
    ANSI_STRIKETHROUGH,

    # Foreground colors
    ANSI_FG_BLACK,
    ANSI_FG_RED,
    ANSI_FG_GREEN,
    ANSI_FG_YELLOW,
    ANSI_FG_BLUE,
    ANSI_FG_MAGENTA,
    ANSI_FG_CYAN,
    ANSI_FG_WHITE,
    ANSI_FG_BRIGHT_BLACK,
    ANSI_FG_BRIGHT_RED,
    ANSI_FG_BRIGHT_GREEN,
    ANSI_FG_BRIGHT_YELLOW,
    ANSI_FG_BRIGHT_BLUE,
    ANSI_FG_BRIGHT_MAGENTA,
    ANSI_FG_BRIGHT_CYAN,
    ANSI_FG_BRIGHT_WHITE,

    # Background colors
    ANSI_BG_BLACK,
    ANSI_BG_RED,
    ANSI_BG_GREEN,
    ANSI_BG_YELLOW,
    ANSI_BG_BLUE,
    ANSI_BG_MAGENTA,
    ANSI_BG_CYAN,
    ANSI_BG_WHITE,
    ANSI_BG_BRIGHT_BLACK,
    ANSI_BG_BRIGHT_RED,
    ANSI_BG_BRIGHT_GREEN,
    ANSI_BG_BRIGHT_YELLOW,
    ANSI_BG_BRIGHT_BLUE,
    ANSI_BG_BRIGHT_MAGENTA,
    ANSI_BG_BRIGHT_CYAN,
    ANSI_BG_BRIGHT_WHITE,

    # Default colors
    ANSI_FG_DEFAULT,
    ANSI_BG_DEFAULT,

    # Color schemes for Go elements
    COLOR_BLACK_STONE,
    COLOR_WHITE_STONE,
    COLOR_BLACK_TERRITORY,
    COLOR_WHITE_TERRITORY,
    COLOR_CONTESTED,
    COLOR_BOARD_BACKGROUND,
    COLOR_COORDINATES,
    COLOR_GRID_LINES,
    COLOR_LAST_MOVE,
    COLOR_HOVER,
    COLOR_INVALID_MOVE,
    COLOR_CAPTURE_HIGHLIGHT,
    COLOR_SCORE_BLACK,
    COLOR_SCORE_WHITE,
    COLOR_WINNER,

    # Helper functions
    is_terminal,
    colorize,
    strip_ansi,
    colored_stone,
    rgb_fg,
    rgb_bg,
    color_256_fg,
    color_256_bg,
)

__all__ = [
    # Symbols
    'SYMBOL_BLACK_STONE',
    'SYMBOL_WHITE_STONE',
    'SYMBOL_BLACK_TERRITORY',
    'SYMBOL_WHITE_TERRITORY',
    'SYMBOL_CONTESTED',
    'SYMBOL_EMPTY',
    'SYMBOL_DISPLAY_WIDTH',
    'get_symbol_legend',

    # ANSI codes
    'ANSI_RESET',
    'ANSI_BOLD',
    'ANSI_DIM',
    'ANSI_ITALIC',
    'ANSI_UNDERLINE',
    'ANSI_BLINK',
    'ANSI_REVERSE',
    'ANSI_HIDDEN',
    'ANSI_STRIKETHROUGH',
    'ANSI_FG_BLACK',
    'ANSI_FG_RED',
    'ANSI_FG_GREEN',
    'ANSI_FG_YELLOW',
    'ANSI_FG_BLUE',
    'ANSI_FG_MAGENTA',
    'ANSI_FG_CYAN',
    'ANSI_FG_WHITE',
    'ANSI_FG_BRIGHT_BLACK',
    'ANSI_FG_BRIGHT_RED',
    'ANSI_FG_BRIGHT_GREEN',
    'ANSI_FG_BRIGHT_YELLOW',
    'ANSI_FG_BRIGHT_BLUE',
    'ANSI_FG_BRIGHT_MAGENTA',
    'ANSI_FG_BRIGHT_CYAN',
    'ANSI_FG_BRIGHT_WHITE',
    'ANSI_BG_BLACK',
    'ANSI_BG_RED',
    'ANSI_BG_GREEN',
    'ANSI_BG_YELLOW',
    'ANSI_BG_BLUE',
    'ANSI_BG_MAGENTA',
    'ANSI_BG_CYAN',
    'ANSI_BG_WHITE',
    'ANSI_BG_BRIGHT_BLACK',
    'ANSI_BG_BRIGHT_RED',
    'ANSI_BG_BRIGHT_GREEN',
    'ANSI_BG_BRIGHT_YELLOW',
    'ANSI_BG_BRIGHT_BLUE',
    'ANSI_BG_BRIGHT_MAGENTA',
    'ANSI_BG_BRIGHT_CYAN',
    'ANSI_BG_BRIGHT_WHITE',
    'ANSI_FG_DEFAULT',
    'ANSI_BG_DEFAULT',

    # Color schemes
    'COLOR_BLACK_STONE',
    'COLOR_WHITE_STONE',
    'COLOR_BLACK_TERRITORY',
    'COLOR_WHITE_TERRITORY',
    'COLOR_CONTESTED',
    'COLOR_BOARD_BACKGROUND',
    'COLOR_COORDINATES',
    'COLOR_GRID_LINES',
    'COLOR_LAST_MOVE',
    'COLOR_HOVER',
    'COLOR_INVALID_MOVE',
    'COLOR_CAPTURE_HIGHLIGHT',
    'COLOR_SCORE_BLACK',
    'COLOR_SCORE_WHITE',
    'COLOR_WINNER',

    # Helper functions
    'is_terminal',
    'colorize',
    'strip_ansi',
    'colored_stone',
    'rgb_fg',
    'rgb_bg',
    'color_256_fg',
    'color_256_bg',
]
